### ISSUE TITLE
Registering builder in conf.py

### ISSUE THREAD

**Issue by rdburns** [shirou/sphinxcontrib-indesignbuilder#1]
I think you have to register this in conf.py as an extension, but I'm not sure of the exact string to use?

**Comment by rdburns** [comment]
I think 'sphinxcontrib.indesignbuilder' is the proper string, that should be added to the readme.rst if so?

**Comment by shirou** [comment]
You mean the name of the builder when specified in the conf.py?
That name is not required same as the python module manner. It is just a short name to specify the builder.

For example, [sphinxcontrib_docbook](https://github.com/HolgerPeters/sphinxcontrib-docbook/blob/master/sphinxcontrib_docbook/__init__.py#L295) use `docbook` as an builder name.

Thank you.

**Comment by rdburns** [comment]
I'm not quite understanding what you're saying. I raised the issue because I think the readme.rst should be modified to explain how to enable the builder in the conf.py, since I believe that is required. It doesn't work otherwise, when I try it.   For example:

``` python
extensions = [
    'sphinx.ext.pngmath', 'rst2pdf.pdfbuilder', 'sphinxcontrib.indesignbuilder'
]
```

Is this the right name to use?

**Comment by shirou** [comment]
Oh, now I got it!

yes, you are right. Now I have added in the README.rst about adding extensions. 

Thank you!
